### ISSUE TITLE
Should be importing CommonModule instead of BrowserModule in expandable-list.module.ts

### ISSUE THREAD

**Issue by TycoT** [andreasonny83/angular2-expandable-list#1]
Hi, I think your expandable-list.module.ts should be importing `CommonModule `instead of `BrowserModule`, or else whoever importing your module would be importing BrowserModule twice into their app, which throws this error:
`Unhandled Promise rejection: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module...`

**Comment by andreasonny83** [comment]
Good spot. Thank you. You should now be able to install the [version 0.2.0](https://github.com/andreasonny83/angular2-expandable-list/releases/tag/v0.2.0) containing that bugfix
