### ISSUE TITLE
clicking on title does not change [isExpanded] variable

### ISSUE THREAD

**Issue by ericalbers** [andreasonny83/angular2-expandable-list#7]
When you click on the title bar and open/close the item, the boolean state of the [isExpanded] variable does not change.

say you have 
<expandable-list-item [isExpanded]="myvariable">   
  <span title> Click me </span>

When you click the Click me, the boolean value of myvariable does not change with the click

**Comment by ericalbers** [comment]
Heres a plunker to play with, note how the toggle button works and the true/false variable  changes with the toggle perfectly, but opening/closing the title fails to update the variable
https://plnkr.co/edit/fBLW5A?p=preview

**Comment by andreasonny83** [comment]
Thank you @ericalbers , I will try to have a look but I'm a little bit out of time at the moment. If you have the chance, send a pull request with the fix and I will be more than happy to accept that in my repository.
Thanks again for your help

**Comment by andreasonny83** [comment]
Hi @ericalbers.
Sorry again about the late. Just an about to let you know that I'm currently looking into this bug

**Comment by andreasonny83** [comment]
@ericalbers let me know if the version 0.5.0 solves your problem and thanks again for your contribution
